# Generated by Django 5.2 on 2025-08-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='KES', max_length=255),
            preserve_default=False,
        ),
    ]
