# Generated by Django 5.2 on 2025-08-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_percent_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
